p8105_hw2_zc2610
================
Zuoqiao Cui
2022-10-01

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readxl)
library(dplyr)
```

## Problem 1

``` r
NYC_transit_data = read.csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
  select(line,station_name,station_latitude,station_longitude,starts_with("route"),entry, exit_only, vending, entrance_type, ada) %>% 
  mutate(
    entry = recode(entry,"YES" = TRUE,"NO" = FALSE),
    route8 = as.character(route8),
    route9 = as.character(route9),
    route10 = as.character(route10),
    route11 = as.character(route11)
  )
```

``` r
num_of_row = nrow(NYC_transit_data)
num_of_column = ncol(NYC_transit_data)
```

Description

1.  There are these variables: line, station_name, station_latitude,
    station_longitude, route1, route2, route3, route4, route5, route6,
    route7, route8, route9, route10, route11, entry, exit_only, vending,
    entrance_type, ada

2.  The process of tidying data is to import, update variable names,
    make all data type of column route to be the same: character, and
    selects the columns that will be used in later parts fo this
    problem. Then, I update `entry` from `yes` / `no` to a logical
    variable.

3.There are totally 1868 rows and 20 columns.

4.  I think it is not tidy enough since there are several columns
    regarding route and they can be combined to a column “route” with
    different numbers as values

Calculate the number of combinations of different station names and
lines

``` r
num_of_combination = NYC_transit_data %>% 
  select(station_name,line) %>% 
  distinct
```

Description There are totally 465 distinct stations

Calculate the number of stations where adas are compliant

``` r
num_of_combination_ada = NYC_transit_data %>%
filter(ada == TRUE) %>% 
  select(station_name,line) %>% 
  distinct
```

Description There are totally 84 distinct stations where adas are
compliant

calculate the proportion of station entrances / exits without vending
allow entrance

``` r
proportion = NYC_transit_data %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
proportion
```

    ## [1] 0.3770492

Description

The proportion of station entrances / exits without vending allow
entrance is 0.3770492

reform route number and route name calculate the number of distinct
stations that serve the A train

``` r
num_a = NYC_transit_data %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

Description

There are totally 60 distinct stations serve the A train

calculate the number of stations that serve the A train and are ADA
compliant

``` r
num_a_ada = NYC_transit_data %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

Description

There are totally 17 distinct stations that serve the A train and are
ADA compliant

## Problem 2

Import, clean, and organize the data for Mr Trash Wheel

``` r
MrTrashWheel_df = 
    read_excel("./data/Trash Wheel Collection Data.xlsx",sheet = "Mr. Trash Wheel",range = "A2:N550") %>% 
    janitor::clean_names() %>% 
    drop_na(dumpster) %>% 
    mutate(
      dumpster = as.character(dumpster),
      sports_balls = as.integer(round(sports_balls)),
      year = as.double(year)
    )
MrTrashWheel_df
```

    ## # A tibble: 547 × 14
    ##    dumpster month  year date                weight_tons volume…¹ plast…² polys…³
    ##    <chr>    <chr> <dbl> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1 1        May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2 2        May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3 3        May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4 4        May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5 5        May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6 6        May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7 7        May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8 8        May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9 9        June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10 10       June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 537 more rows, 6 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, and abbreviated variable names
    ## #   ¹​volume_cubic_yards, ²​plastic_bottles, ³​polystyrene

Import, clean, and organize the data for Professor Trash Wheel

``` r
ProfessorTrashWheel_df = 
    read_excel("./data/Trash Wheel Collection Data.xlsx",sheet = "Professor Trash Wheel",range = "A2:M97") %>% 
    janitor::clean_names() %>% 
    drop_na(dumpster) %>% 
    mutate(
      dumpster = as.character(dumpster)
    )
ProfessorTrashWheel_df
```

    ## # A tibble: 94 × 13
    ##    dumpster month     year date                weight_…¹ volum…² plast…³ polys…⁴
    ##    <chr>    <chr>    <dbl> <dttm>                  <dbl>   <dbl>   <dbl>   <dbl>
    ##  1 1        January   2017 2017-01-02 00:00:00      1.79      15    1950    6080
    ##  2 2        January   2017 2017-01-30 00:00:00      1.58      15    9540   11230
    ##  3 3        February  2017 2017-02-26 00:00:00      2.32      18    8350    9210
    ##  4 4        February  2017 2017-02-26 00:00:00      3.72      15    8590    1030
    ##  5 5        February  2017 2017-02-28 00:00:00      1.45      15    7830    9950
    ##  6 6        March     2017 2017-03-30 00:00:00      1.71      15    8210   10340
    ##  7 7        April     2017 2017-04-01 00:00:00      1.82      15    9830   11020
    ##  8 8        April     2017 2017-04-20 00:00:00      2.37      15    9240    8760
    ##  9 9        May       2017 2017-05-10 00:00:00      2.64      15    9540    8810
    ## 10 10       May       2017 2017-05-26 00:00:00      2.78      15    8230    7800
    ## # … with 84 more rows, 5 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   homes_powered <dbl>, and abbreviated variable names ¹​weight_tons,
    ## #   ²​volume_cubic_yards, ³​plastic_bottles, ⁴​polystyrene

Combine two sheets

``` r
MrTrashWheel_df = MrTrashWheel_df %>% 
 mutate(type = "Mr. Trash Wheel")
ProfessorTrashWheel_df = ProfessorTrashWheel_df %>% 
  mutate(type = "Professor Trash Wheel")
TrashWheel_tidy = bind_rows(MrTrashWheel_df,ProfessorTrashWheel_df) %>% 
  janitor::clean_names() %>% 
  mutate(
    year = as.integer(year)
  )
TrashWheel_tidy
```

    ## # A tibble: 641 × 15
    ##    dumpster month  year date                weight_tons volume…¹ plast…² polys…³
    ##    <chr>    <chr> <int> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1 1        May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2 2        May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3 3        May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4 4        May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5 5        May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6 6        May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7 7        May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8 8        May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9 9        June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10 10       June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 631 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, type <chr>, and abbreviated
    ## #   variable names ¹​volume_cubic_yards, ²​plastic_bottles, ³​polystyrene

Number of observations and variables in Mr Trash Wheel dataset

``` r
num_of_MrTrashWheel_observations = nrow(MrTrashWheel_df)
num_of_MrTrashWheel_variables = ncol(MrTrashWheel_df)
num_of_MrTrashWheel_observations
```

    ## [1] 547

``` r
num_of_MrTrashWheel_variables
```

    ## [1] 15

Number of observations and variables in Mr Trash Wheel dataset

``` r
num_of_ProfessorTrashWheel_observations = nrow(ProfessorTrashWheel_df)
num_of_ProfessorTrashWheel_variables = ncol(ProfessorTrashWheel_df)
num_of_ProfessorTrashWheel_observations
```

    ## [1] 94

``` r
num_of_ProfessorTrashWheel_variables
```

    ## [1] 14

Number of observations and variables in Mr Trash_tidy date frame

``` r
num_of_TrashWheel_tidy_observations = nrow(TrashWheel_tidy) 
num_of_TrashWheel_tidy_variables = ncol(TrashWheel_tidy)
num_of_TrashWheel_tidy_observations
```

    ## [1] 641

``` r
num_of_TrashWheel_tidy_variables
```

    ## [1] 15

Calculate the total weight of trash collected by professor trash wheel

``` r
professor_total_weight = sum(filter(TrashWheel_tidy,type == "Professor Trash Wheel")$weight_tons)
professor_total_weight
```

    ## [1] 190.12

Calculate the total number of sports bals collected by Mr trash wheel

``` r
Mr_total_sportsballs = sum((filter(TrashWheel_tidy,type == "Mr. Trash Wheel",year == 2020)$sports_balls))
Mr_total_sportsballs
```

    ## [1] 856

Description

1.There are totally 547 observations and 15 variables in the Mr Trash
Wheel dataset.

2.There are totally 94 observations and 14 variables in the Professor
Trash Wheel dataset.

3.There are totally 641 observations and 15 variables in the final
combined dataset.

4.Key variables contain “dumpster”,“year”,“weight_tons”,“sports_balls”
and so on. All variables are as followed: dumpster, month, year, date,
weight_tons, volume_cubic_yards, plastic_bottles, polystyrene,
cigarette_butts, glass_bottles, grocery_bags, chip_bags, sports_balls,
homes_powered, type

5.The total weight of trash collected by Professor Trash Wheel is 190.12

6.The total number of sports balls collected by Mr. Trash Wheel in 2020
is 856

## Problem 3

1.  Separate date into year, month and day
2.  Replace month number with month name

``` r
pols_month_df = 
    read_csv("./data/fivethirtyeight_datasets/pols-month.csv") %>% 
    janitor::clean_names() %>% 
    separate(mon,into = c("year","month","day"),sep = "-") %>% 
  mutate(
    month = recode(month, "01" = "January",
                  "02" = "February",
                  "03" = "March",
                  "04" = "April",
                  "05" = "May",
                  "06" = "June",
                  "07" = "July",
                  "08" = "Augest",
                  "09" = "September",
                  "10" = "October",
                  "11" = "November", 
                  "12" = "December"
    )
  )
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pols_month_df
```

    ## # A tibble: 822 × 11
    ##    year  month     day   prez_…¹ gov_gop sen_gop rep_gop prez_…² gov_dem sen_dem
    ##    <chr> <chr>     <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1 1947  January   15          0      23      51     253       1      23      45
    ##  2 1947  February  15          0      23      51     253       1      23      45
    ##  3 1947  March     15          0      23      51     253       1      23      45
    ##  4 1947  April     15          0      23      51     253       1      23      45
    ##  5 1947  May       15          0      23      51     253       1      23      45
    ##  6 1947  June      15          0      23      51     253       1      23      45
    ##  7 1947  July      15          0      23      51     253       1      23      45
    ##  8 1947  Augest    15          0      23      51     253       1      23      45
    ##  9 1947  September 15          0      23      51     253       1      23      45
    ## 10 1947  October   15          0      23      51     253       1      23      45
    ## # … with 812 more rows, 1 more variable: rep_dem <dbl>, and abbreviated
    ## #   variable names ¹​prez_gop, ²​prez_dem

create a president column using values prez_gop and prez_dem

``` r
pols_month_df = pols_month_df %>% 
  mutate(
    president = ifelse(prez_gop == 1, "gop",ifelse(prez_gop == 0,"dem","special case")))
  pols_month_df
```

    ## # A tibble: 822 × 12
    ##    year  month     day   prez_…¹ gov_gop sen_gop rep_gop prez_…² gov_dem sen_dem
    ##    <chr> <chr>     <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1 1947  January   15          0      23      51     253       1      23      45
    ##  2 1947  February  15          0      23      51     253       1      23      45
    ##  3 1947  March     15          0      23      51     253       1      23      45
    ##  4 1947  April     15          0      23      51     253       1      23      45
    ##  5 1947  May       15          0      23      51     253       1      23      45
    ##  6 1947  June      15          0      23      51     253       1      23      45
    ##  7 1947  July      15          0      23      51     253       1      23      45
    ##  8 1947  Augest    15          0      23      51     253       1      23      45
    ##  9 1947  September 15          0      23      51     253       1      23      45
    ## 10 1947  October   15          0      23      51     253       1      23      45
    ## # … with 812 more rows, 2 more variables: rep_dem <dbl>, president <chr>, and
    ## #   abbreviated variable names ¹​prez_gop, ²​prez_dem

remove prez_gop,prez_dem and day variables

``` r
pols_month_df = pols_month_df %>% 
select(-prez_dem,-prez_gop,-day)
pols_month_df
```

    ## # A tibble: 822 × 9
    ##    year  month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <chr> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1 1947  January        23      51     253      23      45     198 dem      
    ##  2 1947  February       23      51     253      23      45     198 dem      
    ##  3 1947  March          23      51     253      23      45     198 dem      
    ##  4 1947  April          23      51     253      23      45     198 dem      
    ##  5 1947  May            23      51     253      23      45     198 dem      
    ##  6 1947  June           23      51     253      23      45     198 dem      
    ##  7 1947  July           23      51     253      23      45     198 dem      
    ##  8 1947  Augest         23      51     253      23      45     198 dem      
    ##  9 1947  September      23      51     253      23      45     198 dem      
    ## 10 1947  October        23      51     253      23      45     198 dem      
    ## # … with 812 more rows

separate date into year, month, day

``` r
snps_df = read_csv("./data/fivethirtyeight_datasets/snp.csv") %>% 
  janitor::clean_names() %>% 
    separate(date,into = c("month","day","year"),sep = "/")
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snps_df
```

    ## # A tibble: 787 × 4
    ##    month day   year  close
    ##    <chr> <chr> <chr> <dbl>
    ##  1 7     1     15    2080.
    ##  2 6     1     15    2063.
    ##  3 5     1     15    2107.
    ##  4 4     1     15    2086.
    ##  5 3     2     15    2068.
    ##  6 2     2     15    2104.
    ##  7 1     2     15    1995.
    ##  8 12    1     14    2059.
    ##  9 11    3     14    2068.
    ## 10 10    1     14    2018.
    ## # … with 777 more rows

arrange year,month and organize them to be leading columns

``` r
snps_df = snps_df %>% 
mutate(
  year = as.integer(year),
  year = ifelse(year < 22,year + 2000,year + 1900)
) 
  snps_df = mutate(snps_df,
    year = as.character(year)
  ) %>% 
  arrange(year,month) %>% 
  relocate(year,month)
  snps_df
```

    ## # A tibble: 787 × 4
    ##    year  month day   close
    ##    <chr> <chr> <chr> <dbl>
    ##  1 1950  1     3      17.0
    ##  2 1950  10    2      19.5
    ##  3 1950  11    1      19.5
    ##  4 1950  12    1      20.4
    ##  5 1950  2     1      17.2
    ##  6 1950  3     1      17.3
    ##  7 1950  4     3      18.0
    ##  8 1950  5     1      18.8
    ##  9 1950  6     1      17.7
    ## 10 1950  7     3      17.8
    ## # … with 777 more rows

switch unemployment dataset from “wide” to “long” format

``` r
unemployment_df = read_csv("./data/fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month", 
    values_to = "percentage of unemployment") %>% 
  mutate(
    year = as.character(year)
  )
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment_df
```

    ## # A tibble: 816 × 3
    ##    year  month `percentage of unemployment`
    ##    <chr> <chr>                        <dbl>
    ##  1 1948  jan                            3.4
    ##  2 1948  feb                            3.8
    ##  3 1948  mar                            4  
    ##  4 1948  apr                            3.9
    ##  5 1948  may                            3.5
    ##  6 1948  jun                            3.6
    ##  7 1948  jul                            3.6
    ##  8 1948  aug                            3.9
    ##  9 1948  sep                            3.8
    ## 10 1948  oct                            3.7
    ## # … with 806 more rows

merge snps dataset into pols dataset and then merge unemployment dataset
into them

``` r
snps_pols_merge = left_join(pols_month_df,snps_df,by = c("year","month"))
merge_unemployment = left_join(snps_pols_merge,unemployment_df,by = c("year","month"))
snps_pols_merge
```

    ## # A tibble: 822 × 11
    ##    year  month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem presi…¹ day  
    ##    <chr> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>   <chr>
    ##  1 1947  January        23      51     253      23      45     198 dem     <NA> 
    ##  2 1947  February       23      51     253      23      45     198 dem     <NA> 
    ##  3 1947  March          23      51     253      23      45     198 dem     <NA> 
    ##  4 1947  April          23      51     253      23      45     198 dem     <NA> 
    ##  5 1947  May            23      51     253      23      45     198 dem     <NA> 
    ##  6 1947  June           23      51     253      23      45     198 dem     <NA> 
    ##  7 1947  July           23      51     253      23      45     198 dem     <NA> 
    ##  8 1947  Augest         23      51     253      23      45     198 dem     <NA> 
    ##  9 1947  September      23      51     253      23      45     198 dem     <NA> 
    ## 10 1947  October        23      51     253      23      45     198 dem     <NA> 
    ## # … with 812 more rows, 1 more variable: close <dbl>, and abbreviated variable
    ## #   name ¹​president

``` r
merge_unemployment
```

    ## # A tibble: 822 × 12
    ##    year  month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem presi…¹ day  
    ##    <chr> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>   <chr>
    ##  1 1947  January        23      51     253      23      45     198 dem     <NA> 
    ##  2 1947  February       23      51     253      23      45     198 dem     <NA> 
    ##  3 1947  March          23      51     253      23      45     198 dem     <NA> 
    ##  4 1947  April          23      51     253      23      45     198 dem     <NA> 
    ##  5 1947  May            23      51     253      23      45     198 dem     <NA> 
    ##  6 1947  June           23      51     253      23      45     198 dem     <NA> 
    ##  7 1947  July           23      51     253      23      45     198 dem     <NA> 
    ##  8 1947  Augest         23      51     253      23      45     198 dem     <NA> 
    ##  9 1947  September      23      51     253      23      45     198 dem     <NA> 
    ## 10 1947  October        23      51     253      23      45     198 dem     <NA> 
    ## # … with 812 more rows, 2 more variables: close <dbl>,
    ## #   `percentage of unemployment` <dbl>, and abbreviated variable name
    ## #   ¹​president

illustration: since the requirement is merge snps into pols, I think all
variables of in pols dataset are more important so that need to be
reserved.Thus, I choose to use left_join. To reserve all variables, I
think full_join can also be used.

Description

1.  pols-month dataset contains variables as followed: year, month,
    gov_gop, sen_gop, rep_gop, gov_dem, sen_dem, rep_dem, president.
    There are totally 822 observations and 9 variables in this dataset.
    The range of year is from 1947 to 2015. Key variables should be
    year, month and president.

2.  snps dataset contains variables as followed: year, month, day,
    close. There are totally 787 observations and 4 variables in this
    dataset. The range of year is from 1950 to 2015. Key variables
    should be year and month.

3.  unemployment dataset contains variables as followed: year, month,
    percentage of unemployment. There are totally 816 observations and 3
    variables in this dataset. The range of year is from 1948 to 2015.
    Key variables should be year and month.

4.  snps_pols_merge dataset is formed by merging snps into pols. This
    dataset contains variables as followed: year, month, gov_gop,
    sen_gop, rep_gop, gov_dem, sen_dem, rep_dem, president, day, close.
    There are totally 822 observations and 11 variables in this dataset.
    The range of year is from 1947 to 2015. Key variables should be year
    and month since snps and pols are joined by these two variables

5.  merge_unemployment dataset is formed by merging unemployment into
    snps_pols_merge. This dataset contains variables as followed: year,
    month, gov_gop, sen_gop, rep_gop, gov_dem, sen_dem, rep_dem,
    president, day, close, percentage of unemployment. There are totally
    822 observations and 12 variables in this dataset. The range of year
    is from 1947 to 2015. Key variables should be year and month since
    unemployment and snps_pols_merge are joined by these two variables
